databases:
  - name: pickupsportsapi
    databaseName: pickupsportsapi
    user: pickupsportsapi
    plan: free

services:
  - type: web
    name: pickupsportsapi
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh" # to create this file
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL # to decrypt sensitive info using a master key
        fromDatabase:
          name: pickupsportsapi
          property: connectionString
      - key: RAILS_MASTER_KEY # use it to decrypt sensitive info
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
